import React, { Component } from 'react';
export default  class Terms extends Component {
  render() {
    let resumeData = this.props.resumeData;
    return (
      <section id="terms">

         <div className="row">
          <h1 style={{marginTop: "80px", color: "#fff"}}>Terms & Conditions</h1>
          <h3 style={{color: "#fff"}}>ArtbyHighEyes and HighEyes are a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the ArtbyhighEyes smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.</h3>
          <h3 style={{color: "#fff"}}>This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving ArtbyHighEyes or HighEyes digital collectibles.</h3>
        </div>

        <div className="row">
        <h1 style={{color: "#fff", marginTop: "25px"}}>Ownership</h1>
        <h3 style={{color: "#fff"}}>i. You Own the NFT. Each ArtbyHighEyes art piece is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying ArtbyHighEyes art piece, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any ArtbyHighEyes art piece.</h3>
        <h3 style={{color: "#fff"}}>ii. Personal Use. Subject to your continued compliance with these Terms, ArtbyHighEyes grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your ArtbyHighEyes art piece / NFT, provided that the marketplace cryptographically verifies each ArtbyHighEyes art piece owner’s rights to display the Art for their art piece to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your art piece, provided that the website/application cryptographically verifies each art piece owner’s rights to display the Art for their art piece to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the art piece leaves the website/application.</h3>
        <h3 style={{color: "#fff"}}>iii. Commercial Use. Subject to your continued compliance with these Terms, ArtbyHighEyes grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of ArtbyHighEyes art pieces generally, provided that the marketplace cryptographically verifies each ArtbyHighEyes art piece owner’s rights to display the Art for their ArtbyHighEyes art piece to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of ArtbyHighEyes art pieces generally, provided that the third party website or application cryptographically verifies each ArtbyHighEyes art pieces owner’s rights to display the Art for their  ArtbyHighEyes art piece to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased  ArtbyHighEyes art piece leaves the website/application; or (iii) earning revenue from any of the foregoing.</h3>
         </div>

      </section>
    );
  }
}